In [7]:
import mir_eval
import numpy as np

In [8]:
mir_eval.separation.bss_eval_sources

<function mir_eval.separation.bss_eval_sources(reference_sources, estimated_sources, compute_permutation=True)>

In [9]:
voices = np.load('datasets/voices_sr8000_dur5.npy')
noises = np.load('datasets/noises_sr8000_dur5.npy')

In [13]:
sources = np.stack((voices[0], noises[0]))

In [21]:
mir_eval.separation.bss_eval_sources(sources, sources)

(array([276.15648954, 258.11776949]),
 array([291.84691549, 246.70462771]),
 array([276.1568244 , 246.30826499]),
 array([0, 1]))

In [5]:
import pytorch_ssim
import torch

img1 = torch.rand(1, 1, 256, 256)
img2 = torch.rand(1, 1, 256, 256)

print(pytorch_ssim.ssim(img1, img2))

# ssim_loss = pytorch_ssim.SSIM(window_size = 11)

# print(ssim_loss(img1, img2))

tensor(0.0208)
